name: epilearn
description: A Flutter app to explore Rick and Morty episodes using clean architecture.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  dio: ^5.4.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2

 
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  build_runner: ^2.4.8
  freezed: ^2.5.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
